[package]
name = "rp-rs"
version = "0.1.0"
authors = ["hugsy <hugsy@blah.cat>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
goblin = "0.2.3"
capstone = "0.7.0"
clap = "3.0.0-beta.1"
colored = "2"
bitflags = "1.2.1"
log = {version = "0.4.11", features = ["std",]}